"""rename address to location

Revision ID: c9e445a6b4d4
Revises: caf765081133
Create Date: 2025-03-25 15:22:32.510392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e445a6b4d4'
down_revision = 'caf765081133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name = 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name = 'address')
    # ### end Alembic commands ###
